spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:8889
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update


security:
  basic:
    enabled: false
server:
  port: ${SERVER_PORT:8090}

spring.http.multipart.max-file-size: ${UPLOAD_MAX_SIZE:10MB}
spring.http.multipart.max-request-size: ${UPLOAD_MAX_SIZE:10MB}
